#-*- coding: utf-8 -*-
#encoding: utf-8
import Functions as fct
beta = 'Isso e um beta'
h1 = '{size: 54px; text-align: center;\n\tfont-family: Georgia, \'Times New Roman\', Times, serif;}'
h2 = '{size: 40px; text-align: center;\n\tfont-family: Georgia, \'Times New Roman\', Times, serif;}'
body ='{text-align: justify;\n\tmax-width: 650px;\n\tfont-family: Georgia, \'Times New Roman\', Times, serif;\n\tfont-size: 16px;\n\tpadding: 0;\n\tmargin: 0 auto !important;}'

def escrever_contrato():
    Contratohtml = open('Contrato.html', 'w', encoding = 'utf-8')
    Contratohtml.write(f'<!DOCTYPE>\n\t<html>\n\t<meta charset="utf-8">\n\t<meta name="viewport" content="width=297x420" initialscale="1">\n\t<title>Template Autotech</title>\n\t<style>\n\th1 {h1}\n\th2 {h2}\n\tbody {body}\n\t</style>\n\t<head>\n\t<h1>{fct.NomeEJ}</h1>\n\t<h2>CONTRATO DE PRESTAÇÃO DE SERVIÇOS</h2\n\t<h3>CONTROLE: {fct.NumeroControle}</h3>\n\t<br>\n\t<br>\n\t</head>\n\t<body>\n\t<p><strong>Celebrado consoante a melhor forma de Direito e consoante todas as disposições legais pertinentes à matéria, firmam entre si o presente contrato de prestação de serviços, por justo e acertado, as partes abaixo qualificadas:</strong></p>\n\t<br>\n\t<p><strong>CONTRATANTE: {fct.NomeEmpresa}</strong> pessoa jurídica, de direito privado, denominado <strong>CONTRATANTE</strong>, devidamente constituída como sociedade limitada, inscrita no CNPJ sob o n° {fct.CNPJCliente}, com endereço {fct.EnderecoCliente} , CEP n° {fct.CEPcliente}, {fct.CidadeEstadoCliente}, neste ato representada por seu Presidente <strong>{fct.PresidenteCliente}</strong>, inscrito no CPF sob o n° {fct.CPFPresidenteCliente} e no RG Nº {fct.RGPresidenteCliente}, residente e domiciliado em {fct.EnderecoCliente}.</p>\n\t<p><strong>CONTRATADA: {fct.NomeEJ}</strong>, pessoa jurídica de direito privado, denominada <strong>CONTRATADA</strong>, devidamente constituída como associação civil sem fins lucrativos, inscrita no CNPJ sob o n° {fct.CNPJEJ}, com endereço à , CEP {fct.CEPEJ}, Fortaleza, Ceará, neste ato representada por seu diretor presidente, <strong>{fct.PresidenteEJ}</strong>, inscrito no CPF n° {fct.CPFPresidenteEJ}, portador da identidade nº {fct.RGPresidenteEJ}, residente e domiciliado em {fct.EnderecoPresidenteEJ}.</p>')
    Contratohtml.close()